# Generated by Django 4.1.1 on 2022-09-26 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'commune',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('short_description', models.CharField(default='', max_length=100)),
                ('long_description', models.CharField(max_length=200, null=True)),
                ('qty_rooms', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('department_image', models.BinaryField(blank=True, null=True)),
                ('commune_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='department_commune_id_fk', to='api_rest.commune')),
            ],
            options={
                'db_table': 'department',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'department_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mail_address', models.EmailField(max_length=100)),
                ('profile_photo', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('guarantee_payment', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('total_payment', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'region',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'reservation_status',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServicesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'service_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('hire_date', models.DateField()),
            ],
            options={
                'db_table': 'tour',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('id_vehicle', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vehicle',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'work_area',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('location', models.CharField(default=None, max_length=250, null=True)),
                ('available', models.BooleanField(default=False)),
                ('service_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='service_type_fk', to='api_rest.servicestype')),
            ],
            options={
                'db_table': 'service',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_customer', models.IntegerField(default=1)),
                ('reservation_date', models.DateField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('id_customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='r_id_customer_fk', to='api_rest.customer')),
                ('id_department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='r_id_department_fk', to='api_rest.department')),
                ('id_employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='r_id_employee_fk', to='api_rest.employee')),
                ('id_payment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='r_id_payment_fk', to='api_rest.payment')),
                ('id_reservation_status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='r_id_reservation_status_fk', to='api_rest.reservationstatus')),
                ('id_service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='r_id_service_fk', to='api_rest.services')),
                ('id_vehicle', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='r_id_vehicle_fk', to='api_rest.vehicle')),
            ],
            options={
                'db_table': 'reservation',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff', models.IntegerField(default=0)),
                ('rental_date', models.DateField()),
                ('payment_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payment_id_fk', to='api_rest.payment')),
            ],
            options={
                'db_table': 'rent',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('product_image', models.BinaryField(blank=True, null=True)),
                ('product_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_type_fk', to='api_rest.producttype')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(default=0)),
                ('egress', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('date_time', models.DateField()),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='finance_user_id_fk', to='api_rest.employee')),
            ],
            options={
                'db_table': 'finance',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('work_area_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='work_area_id_fk', to='api_rest.workarea')),
            ],
            options={
                'db_table': 'employee_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='session_user_id_fk', to='api_rest.employee')),
            ],
            options={
                'db_table': 'employee_session',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_fk', to='api_rest.employee')),
            ],
            options={
                'db_table': 'employee_account',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employee_type_id_fk', to='api_rest.employeetype'),
        ),
        migrations.CreateModel(
            name='DepartmentMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('last_maintenance', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('department_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='department_maintance_id_fk', to='api_rest.department')),
            ],
            options={
                'db_table': 'department_maintenance',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('qty', models.IntegerField(default=0)),
                ('department_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='department_id_fk', to='api_rest.department')),
                ('product_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_id_fk', to='api_rest.product')),
            ],
            options={
                'db_table': 'department_inventory',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='department_type_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='department_type_id_fk', to='api_rest.departmenttype'),
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('regular_customer', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer_user_id_fk', to='api_rest.customer')),
            ],
            options={
                'db_table': 'customer_account',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mail_address', models.CharField(max_length=100)),
                ('legal_representative', models.CharField(max_length=100)),
                ('commune_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='commune_id_fk', to='api_rest.commune')),
            ],
            options={
                'db_table': 'company',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='commune',
            name='id_region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_region_fk', to='api_rest.region'),
        ),
    ]
