# Generated by Django 4.1.1 on 2022-10-01 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'commune',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('short_description', models.CharField(default='', max_length=100)),
                ('long_description', models.CharField(max_length=200, null=True)),
                ('qty_rooms', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('department_image', models.BinaryField(blank=True, null=True)),
                ('commune', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='department_commune_id_fk', to='api_rest.commune')),
            ],
            options={
                'db_table': 'department',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentDisponibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nuevo', 'Nuevo'), ('mantenimiento', 'Departamento en mantención')], max_length=200)),
                ('maintance_init', models.DateField(default=None, null=True)),
                ('maintance_finish', models.DateField(default=None, null=True)),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='department_disponibility_fk', to='api_rest.department')),
            ],
            options={
                'db_table': 'department_disponibility',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'department_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mail_address', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'employee',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'region',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(null=True)),
                ('reservation_amount', models.IntegerField(null=True)),
                ('qty_customers', models.IntegerField(blank=True, null=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('department_disponibility', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_rest.departmentdisponibility')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservation',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServicesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'service_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'work_area',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('location', models.CharField(default=None, max_length=250, null=True)),
                ('available', models.BooleanField(default=False)),
                ('service_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='service_type_fk', to='api_rest.servicestype')),
            ],
            options={
                'db_table': 'service',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReservationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_rest.services')),
                ('reservation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_rest.reservation')),
            ],
            options={
                'db_table': 'reservation_details',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('product_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_type_fk', to='api_rest.producttype')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(default=0)),
                ('egress', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('date_time', models.DateField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='finance_user_id_fk', to='api_rest.employee')),
            ],
            options={
                'db_table': 'finance',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('work_area', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='work_area_id_fk', to='api_rest.workarea')),
            ],
            options={
                'db_table': 'employee_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='session_user_id_fk', to='api_rest.employee')),
            ],
            options={
                'db_table': 'employee_session',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_fk', to='api_rest.employee')),
            ],
            options={
                'db_table': 'employee_account',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employee_type_id_fk', to='api_rest.employeetype'),
        ),
        migrations.CreateModel(
            name='DepartmentInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('qty', models.IntegerField(default=0)),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='department_id_fk', to='api_rest.department')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_id_fk', to='api_rest.product')),
            ],
            options={
                'db_table': 'department_inventory',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='department_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='department_type_id_fk', to='api_rest.departmenttype'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mail_address', models.CharField(max_length=100)),
                ('legal_representative', models.CharField(max_length=100)),
                ('commune', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='commune_id_fk', to='api_rest.commune')),
            ],
            options={
                'db_table': 'company',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='commune',
            name='region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_region_fk', to='api_rest.region'),
        ),
    ]
