# Generated by Django 4.1.1 on 2022-09-12 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_maintenance_id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='heating',
        ),
        migrations.RemoveField(
            model_name='department',
            name='internet',
        ),
        migrations.RemoveField(
            model_name='department',
            name='tv_cable',
        ),
        migrations.AddField(
            model_name='departmentmaintenance',
            name='department_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='department_maintance_id_fk', to='api_rest.department'),
        ),
    ]
