# Generated by Django 4.1.1 on 2022-10-01 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='department_disponibility',
        ),
        migrations.AddField(
            model_name='reservation',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_rest.department'),
        ),
        migrations.AlterField(
            model_name='departmentdisponibility',
            name='status',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('mantenimiento', 'Departamento en mantención')], max_length=200, null=True),
        ),
    ]
