# Generated by Django 4.1.1 on 2022-09-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_remove_department_department_maintenance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='long_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='short_description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
