# Generated by Django 4.1.1 on 2022-09-27 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_rest', '0002_rename_id_region_commune_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentDisponibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reservado', 'Reservado'), ('disponible', 'Disponible'), ('nuevo', 'Nuevo'), ('mantenimiento', 'Departamento en mantención')], max_length=200)),
                ('maintance_init', models.DateField(default=None)),
                ('maintance_finish', models.DateField(default=None)),
                ('start_reservation', models.DateField(default=None)),
                ('finish_resercation', models.DateField(default=None)),
            ],
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.RemoveField(
            model_name='department',
            name='status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='qty_customer',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_status',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='service',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='reservation',
            name='difference_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='qty_customers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='services',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api_rest.services'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reservado', 'Reservado (10% pagado)'), ('pagado', 'Pagado (100%)'), ('cancelado', 'Cancelado')], default='reservado', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api_rest.department'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name='reservation',
            table=None,
        ),
        migrations.DeleteModel(
            name='DepartmentMaintenance',
        ),
        migrations.DeleteModel(
            name='ReservationStatus',
        ),
        migrations.AddField(
            model_name='departmentdisponibility',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='department_disponibility_fk', to='api_rest.department'),
        ),
    ]
