# Generated by Django 4.1.1 on 2022-09-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_alter_departmentdisponibility_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='reservation',
        ),
    ]
