# Generated by Django 4.1.1 on 2022-09-29 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_alter_reservation_options_alter_reservation_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerAccount',
        ),
    ]
