# Generated by Django 4.1.1 on 2022-09-29 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_rest', '0006_remove_customeraccount_user_delete_tour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_rest.department'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='services',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
