# Generated by Django 4.1.1 on 2022-10-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0007_reservation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='reservation_date',
        ),
    ]
