# Generated by Django 4.1.1 on 2022-10-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0008_rename_date_reservation_reservation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(default=0),
        ),
    ]
