# Generated by Django 4.1.1 on 2022-10-18 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0009_rename_reservation_date_reservation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='reseravation_date',
        ),
    ]
