# Generated by Django 4.1.1 on 2022-10-19 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0010_rename_date_reservation_reseravation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reseravation_date',
            new_name='reservation_date',
        ),
    ]
