# Generated by Django 4.1.1 on 2022-10-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0011_rename_reseravation_date_reservation_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='ok', max_length=100),
        ),
    ]
